# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class DiceTerm(BaseModel):
    # DiceTerm
    # Purpose
    # -------
    # Represents a single dice term NdS (e.g., 2d6).
    # 
    # Fields
    # ------
    # - count: number of dice (>= 1)
    # - sides: number of sides per die (>= 2)
    # 
    # Invariants
    # ----------
    # - count must be >= 1.
    # - sides must be >= 2.
    # 
    # Notes
    # -----
    # Multiple DiceTerm entries may be combined within a RollPlan.

    count: typing.Optional[int] = None
    sides: typing.Optional[int] = None

class RollPlan(BaseModel):
    # RollPlan
    # 
    # Purpose
    # -------
    # Encodes a fully specified, deterministic dice execution plan that can be
    # executed by host runtime code.
    # 
    # Fields
    # ------
    # - dice: list of DiceTerm entries defining all dice rolled per instance.
    # - modifier: flat integer modifier applied once per instance.
    # - repeat: number of independent instances to execute (>= 1).
    # - mode: RollMode indicating d20 resolution behavior.
    # - label: optional short description for UI/logging.
    # 
    # Invariants
    # ----------
    # - repeat must be >= 1.
    # - modifier applies once per instance, never per die.
    # - mode affects only d20 terms.
    # 
    # Notes
    # -----
    # RollPlan must be directly executable without additional inference.

    dice: typing.List["DiceTerm"]
    modifier: typing.Optional[int] = None
    repeat: typing.Optional[int] = None
    mode: typing.Optional[types.RollMode] = None
    label: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
