# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DiceTerm": types.DiceTerm,
    "stream_types.DiceTerm": stream_types.DiceTerm,

    "types.RollPlan": types.RollPlan,
    "stream_types.RollPlan": stream_types.RollPlan,


    "types.RollMode": types.RollMode,

}