# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class RollMode(str, Enum):
    # RollMode
# 
# Purpose
# -------
# Represents how a d20 roll should be resolved under D&D 5e rules.
# 
# Fields
# ------
# - NORMAL: single d20 roll.
# - ADVANTAGE: roll two d20 and keep the higher.
# - DISADVANTAGE: roll two d20 and keep the lower.
# 
# Invariants
# ----------
# - Only meaningful if at least one DiceTerm has sides=20.
# 
# Notes
# -----
# Host runtime is responsible for enforcing advantage mechanics.
    NORMAL = "NORMAL"
    ADVANTAGE = "ADVANTAGE"
    DISADVANTAGE = "DISADVANTAGE"

# #########################################################################
# Generated classes (2)
# #########################################################################

class DiceTerm(BaseModel):
    # DiceTerm
    # Purpose
    # -------
    # Represents a single dice term NdS (e.g., 2d6).
    # 
    # Fields
    # ------
    # - count: number of dice (>= 1)
    # - sides: number of sides per die (>= 2)
    # 
    # Invariants
    # ----------
    # - count must be >= 1.
    # - sides must be >= 2.
    # 
    # Notes
    # -----
    # Multiple DiceTerm entries may be combined within a RollPlan.

    count: int
    sides: int

class RollPlan(BaseModel):
    # RollPlan
    # 
    # Purpose
    # -------
    # Encodes a fully specified, deterministic dice execution plan that can be
    # executed by host runtime code.
    # 
    # Fields
    # ------
    # - dice: list of DiceTerm entries defining all dice rolled per instance.
    # - modifier: flat integer modifier applied once per instance.
    # - repeat: number of independent instances to execute (>= 1).
    # - mode: RollMode indicating d20 resolution behavior.
    # - label: optional short description for UI/logging.
    # 
    # Invariants
    # ----------
    # - repeat must be >= 1.
    # - modifier applies once per instance, never per die.
    # - mode affects only d20 terms.
    # 
    # Notes
    # -----
    # RollPlan must be directly executable without additional inference.

    dice: typing.List["DiceTerm"]
    modifier: int
    repeat: int
    mode: RollMode
    label: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
